name: Intraday Scanner Live

on:
  schedule:
    # Every weekday at 9:30, 10:30, 11:30 IST (4:00, 5:30, 6:30 UTC)
    - cron: '0 4 * * 1-5'
    - cron: '30 5 * * 1-5'
    - cron: '30 6 * * 1-5'
  workflow_dispatch:  # Manual trigger if needed

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Intraday Scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python india-intraday-scanner.py --test  # remove --test for real trades
